/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewsIndexRouteImport } from './routes/views.index'
import { Route as ViewsOnboardingRouteImport } from './routes/views.onboarding'
import { Route as ViewsLoginRouteImport } from './routes/views.login'

const ViewsIndexRoute = ViewsIndexRouteImport.update({
  id: '/views/',
  path: '/views/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsOnboardingRoute = ViewsOnboardingRouteImport.update({
  id: '/views/onboarding',
  path: '/views/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewsLoginRoute = ViewsLoginRouteImport.update({
  id: '/views/login',
  path: '/views/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/views/login': typeof ViewsLoginRoute
  '/views/onboarding': typeof ViewsOnboardingRoute
  '/views/': typeof ViewsIndexRoute
}
export interface FileRoutesByTo {
  '/views/login': typeof ViewsLoginRoute
  '/views/onboarding': typeof ViewsOnboardingRoute
  '/views': typeof ViewsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/views/login': typeof ViewsLoginRoute
  '/views/onboarding': typeof ViewsOnboardingRoute
  '/views/': typeof ViewsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/views/login' | '/views/onboarding' | '/views/'
  fileRoutesByTo: FileRoutesByTo
  to: '/views/login' | '/views/onboarding' | '/views'
  id: '__root__' | '/views/login' | '/views/onboarding' | '/views/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ViewsLoginRoute: typeof ViewsLoginRoute
  ViewsOnboardingRoute: typeof ViewsOnboardingRoute
  ViewsIndexRoute: typeof ViewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/views/': {
      id: '/views/'
      path: '/views'
      fullPath: '/views/'
      preLoaderRoute: typeof ViewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/onboarding': {
      id: '/views/onboarding'
      path: '/views/onboarding'
      fullPath: '/views/onboarding'
      preLoaderRoute: typeof ViewsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/views/login': {
      id: '/views/login'
      path: '/views/login'
      fullPath: '/views/login'
      preLoaderRoute: typeof ViewsLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ViewsLoginRoute: ViewsLoginRoute,
  ViewsOnboardingRoute: ViewsOnboardingRoute,
  ViewsIndexRoute: ViewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
