/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UiCheckoutRouteImport } from './routes/ui.checkout'
import { Route as SurfaceModalRouteImport } from './routes/surface.modal'
import { Route as InteractionsViewTransitionsRouteImport } from './routes/interactions.view-transitions'
import { Route as InteractionsInputRouteImport } from './routes/interactions.input'
import { Route as InteractionsHoverRouteImport } from './routes/interactions.hover'

const UiCheckoutRoute = UiCheckoutRouteImport.update({
  id: '/ui/checkout',
  path: '/ui/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SurfaceModalRoute = SurfaceModalRouteImport.update({
  id: '/surface/modal',
  path: '/surface/modal',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsViewTransitionsRoute =
  InteractionsViewTransitionsRouteImport.update({
    id: '/interactions/view-transitions',
    path: '/interactions/view-transitions',
    getParentRoute: () => rootRouteImport,
  } as any)
const InteractionsInputRoute = InteractionsInputRouteImport.update({
  id: '/interactions/input',
  path: '/interactions/input',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractionsHoverRoute = InteractionsHoverRouteImport.update({
  id: '/interactions/hover',
  path: '/interactions/hover',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/interactions/hover': typeof InteractionsHoverRoute
  '/interactions/input': typeof InteractionsInputRoute
  '/interactions/view-transitions': typeof InteractionsViewTransitionsRoute
  '/surface/modal': typeof SurfaceModalRoute
  '/ui/checkout': typeof UiCheckoutRoute
}
export interface FileRoutesByTo {
  '/interactions/hover': typeof InteractionsHoverRoute
  '/interactions/input': typeof InteractionsInputRoute
  '/interactions/view-transitions': typeof InteractionsViewTransitionsRoute
  '/surface/modal': typeof SurfaceModalRoute
  '/ui/checkout': typeof UiCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/interactions/hover': typeof InteractionsHoverRoute
  '/interactions/input': typeof InteractionsInputRoute
  '/interactions/view-transitions': typeof InteractionsViewTransitionsRoute
  '/surface/modal': typeof SurfaceModalRoute
  '/ui/checkout': typeof UiCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/interactions/hover'
    | '/interactions/input'
    | '/interactions/view-transitions'
    | '/surface/modal'
    | '/ui/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/interactions/hover'
    | '/interactions/input'
    | '/interactions/view-transitions'
    | '/surface/modal'
    | '/ui/checkout'
  id:
    | '__root__'
    | '/interactions/hover'
    | '/interactions/input'
    | '/interactions/view-transitions'
    | '/surface/modal'
    | '/ui/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  InteractionsHoverRoute: typeof InteractionsHoverRoute
  InteractionsInputRoute: typeof InteractionsInputRoute
  InteractionsViewTransitionsRoute: typeof InteractionsViewTransitionsRoute
  SurfaceModalRoute: typeof SurfaceModalRoute
  UiCheckoutRoute: typeof UiCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ui/checkout': {
      id: '/ui/checkout'
      path: '/ui/checkout'
      fullPath: '/ui/checkout'
      preLoaderRoute: typeof UiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surface/modal': {
      id: '/surface/modal'
      path: '/surface/modal'
      fullPath: '/surface/modal'
      preLoaderRoute: typeof SurfaceModalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions/view-transitions': {
      id: '/interactions/view-transitions'
      path: '/interactions/view-transitions'
      fullPath: '/interactions/view-transitions'
      preLoaderRoute: typeof InteractionsViewTransitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions/input': {
      id: '/interactions/input'
      path: '/interactions/input'
      fullPath: '/interactions/input'
      preLoaderRoute: typeof InteractionsInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactions/hover': {
      id: '/interactions/hover'
      path: '/interactions/hover'
      fullPath: '/interactions/hover'
      preLoaderRoute: typeof InteractionsHoverRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  InteractionsHoverRoute: InteractionsHoverRoute,
  InteractionsInputRoute: InteractionsInputRoute,
  InteractionsViewTransitionsRoute: InteractionsViewTransitionsRoute,
  SurfaceModalRoute: SurfaceModalRoute,
  UiCheckoutRoute: UiCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
